cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="$env:CMAKE_BUILDS_PREFIX" -DCMAKE_INSTALL_PREFIX="$env:CMAKE_BUILDS_PREFIX" `
       -DIMGUI_DIR="$env:IMGUI_FOR_DCS_PATH" -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -- -j4
