cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX \
       -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13\
       -DIMGUI_DIR=$IMGUI_FOR_DCS_PATH \
       -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -- -j4
