cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX \
       -DBUILD_STATIC=true -DBUILD_STATIC_PIC=true -DBUILD_PLUGINS_STATIC=true -DWITH_TINYGLTFIMPORTER=true -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target install -- -j4
