cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 \
      -DBUILD_STATIC=true -DBUILD_STATIC_PIC=true -DWITH_IMGUI=true \
      -DIMGUI_DIR=$IMGUI_FOR_DCS_PATH \
      -DCMAKE_BUILD_TYPE=${DCS_BUILD_TYPE:-Debug} \
      -G"Ninja" ..
cmake --build . --target install 
