cmake -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX \
       -DBUILD_STATIC=true -DBUILD_STATIC_PIC=true -DBUILD_PLUGINS_STATIC=true -DWITH_TINYGLTFIMPORTER=true -DCMAKE_BUILD_TYPE=Release ..
make -j4
make install
