cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13\
    -DBUILD_STATIC=true -DBUILD_STATIC_PIC=true -DWITH_ANYIMAGEIMPORTER=true -DBUILD_PLUGINS_STATIC=true -DWITH_GLFWAPPLICATION=true -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target install -- -j4
