cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13\
      -DBUILD_STATIC=true -DBUILD_STATIC_PIC=true -DBUILD_PLUGINS_STATIC=true\ 
      -DWITH_ANYIMAGEIMPORTER=true -DCMAKE_BUILD_TYPE=Release\
      -G"Ninja" ..
cmake -DWITH_SDL2APPLICATION=ON . || cmake -DWITH_SDL2APPLICATION=OFF .
cmake -DWITH_GLFWAPPLICATION=ON . || cmake -DWITH_GLFWAPPLICATION=OFF .
cmake --build . --target install
