cmake -DCMAKE_PREFIX_PATH=$CMAKE_BUILDS_PREFIX -DCMAKE_INSTALL_PREFIX=$CMAKE_BUILDS_PREFIX\
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13\
      -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=false\
      -G"Ninja" ..
cmake --build . --target install
